=== silagokth/vesyla/modules/vs-component/assets/arch_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "platform": {
      "type": "string",
      "enum": [
        "drra"
      ]
    },
    "resources": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/resource"
      }
    },
    "controllers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/controller"
      }
    },
    "cells": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/cell"
      }
    },
    "fabric": {
      "$ref": "#/definitions/fabric"
    },
    "interface": {
      "$ref": "#/definitions/interface"
    }
  },
  "required": [
    "platform",
    "resources",
    "controllers",
    "cells",
    "fabric",
    "interface"
  ],
  "additionalProperties": false,
  "definitions": {
    "resource": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "size": {
          "type": "integer",
          "minimum": 1
        },
        "word_input_port": {
          "type": "integer",
          "minimum": 0
        },
        "word_output_port": {
          "type": "integer",
          "minimum": 0
        },
        "bulk_input_port": {
          "type": "integer",
          "minimum": 0
        },
        "bulk_output_port": {
          "type": "integer",
          "minimum": 0
        },
        "custom_properties": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "key": {
                "type": "string"
              },
              "val": {
                "type": "integer",
                "minimum": 0
              }
            },
            "required": [
              "key",
              "val"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "name",
        "size"
      ]
    },
    "controller": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "size": {
          "type": "integer",
          "minimum": 1
        },
        "iram_size": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "name",
        "size"
      ]
    },
    "cell": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "controller": {
          "type": "string"
        },
        "resource_list": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "controller",
        "resource_list"
      ]
    },
    "fabric": {
      "type": "object",
      "properties": {
        "cell_lists": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "coordinates": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "row": {
                      "type": "integer",
                      "minimum": 0
                    },
                    "col": {
                      "type": "integer",
                      "minimum": 0
                    }
                  },
                  "required": [
                    "row",
                    "col"
                  ]
                }
              },
              "cell_name": {
                "type": "string"
              }
            },
            "required": [
              "coordinates",
              "cell_name"
            ]
          }
        },
        "custom_properties": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "key": {
                "type": "string"
              },
              "val": {
                "type": "integer"
              }
            },
            "required": [
              "key",
              "val"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "cell_lists"
      ]
    },
    "interface": {
      "type": "object",
      "properties": {
        "input_buffer_depth": {
          "type": "integer",
          "minimum": 1
        },
        "output_buffer_depth": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "input_buffer_depth",
        "output_buffer_depth"
      ]
    }
  }
}

=== silagokth/vesyla/modules/vs-testcase/testcase/drra/transformer/softmax_max_4_column/arch.json
{
  "platform": "drra",
  "resources": [
    {
      "name": "iosram",
      "size": 4,
      "word_input_port": 0,
      "word_output_port": 0,
      "bulk_input_port": 2,
      "bulk_output_port": 2,
      "custom_properties": [
        {
          "key": "depth",
          "val": 64
        }
      ]
    },
    {
      "name": "swb",
      "size": 1,
      "word_input_port": 0,
      "word_output_port": 0,
      "bulk_input_port": 0,
      "bulk_output_port": 0
    },
    {
      "name": "dpu",
      "size": 2,
      "word_input_port": 2,
      "word_output_port": 1,
      "bulk_input_port": 0,
      "bulk_output_port": 0
    },
    {
      "name": "rf",
      "size": 1,
      "word_input_port": 1,
      "word_output_port": 1,
      "bulk_input_port": 1,
      "bulk_output_port": 1,
      "custom_properties": [
        {
          "key": "depth",
          "val": 64
        }
      ]
    }
  ],
  "controllers": [
    {
      "name": "controller_io",
      "size": 8,
      "iram_size": 64
    },
    {
      "name": "controller_normal",
      "size": 16,
      "iram_size": 64
    }
  ],
  "cells": [
    {
      "name": "drra_cell_input",
      "controller": "controller_io",
      "resource_list": ["swb", "iosram"]
    },
    {
      "name": "drra_cell_output",
      "controller": "controller_io",
      "resource_list": ["swb", "iosram"]
    },
    {
      "name": "drra_cell_normal",
      "controller": "controller_normal",
      "resource_list": ["swb", "rf", "rf", "rf", "dpu"]
    }
  ],
  "fabric": {
    "height": 4,
    "width": 4,
    "cell_lists": [
      {
        "coordinates": [{ "row": 0, "col": 0 }],
        "cell_name": "drra_cell_input"
      },
      {
        "coordinates": [{ "row": 1, "col": 0 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 2, "col": 0 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 3, "col": 0 }],
        "cell_name": "drra_cell_output"
      },
      {
        "coordinates": [{ "row": 0, "col": 1 }],
        "cell_name": "drra_cell_input"
      },
      {
        "coordinates": [{ "row": 1, "col": 1 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 2, "col": 1 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 3, "col": 1 }],
        "cell_name": "drra_cell_output"
      },
      {
        "coordinates": [{ "row": 0, "col": 2 }],
        "cell_name": "drra_cell_input"
      },
      {
        "coordinates": [{ "row": 1, "col": 2 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 2, "col": 2 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 3, "col": 2 }],
        "cell_name": "drra_cell_output"
      },
      {
        "coordinates": [{ "row": 0, "col": 3 }],
        "cell_name": "drra_cell_input"
      },
      {
        "coordinates": [{ "row": 1, "col": 3 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 2, "col": 3 }],
        "cell_name": "drra_cell_normal"
      },
      {
        "coordinates": [{ "row": 3, "col": 3 }],
        "cell_name": "drra_cell_output"
      }
    ],
    "custom_properties": []
  },
  "interface": {
    "input_buffer_depth": 1024,
    "output_buffer_depth": 1024
  }
}
