=== silagokth/vesyla/modules/vs-component/assets/component_arch_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "kind": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "resource",
        "controller"
      ]
    },
    "category": {
      "type": "string",
      "enum": [
        "uncategorized",
        "processor",
        "memory",
        "network",
        "system"
      ],
      "default": "uncategorized"
    },
    "size": {
      "type": "integer",
      "minimum": 1,
      "default": 1
    },
    "io_input": {
      "type": "boolean",
      "default": false
    },
    "io_output": {
      "type": "boolean",
      "default": false
    },
    "custom_properties": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "value": {
            "type": "number"
          }
        },
        "required": [
          "name",
          "value"
        ],
        "additionalProperties": false
      },
      "default": []
    },
    "required_parameters": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    }
  },
  "required": [
    "kind"
  ]
}

=== silagokth/vesyla/module/vs-component/components/resources/iosram_btm/arch.json
{
  "kind": "iosram_btm",
  "size": 4,
  "io_input": false,
  "io_output": true,
  "custom_properties": [
    {
      "name": "SRAM_ADDR_WIDTH",
      "value": 6
    }
  ],
  "required_parameters": [
    "IO_DATA_WIDTH",
    "IO_ADDR_WIDTH",
    "RESOURCE_INSTR_WIDTH",
    "BULK_BITWIDTH",
    "WORD_BITWIDTH",
    "NUM_SLOTS",
    "FSM_PER_SLOT",
    "INSTR_OPCODE_BITWIDTH"
  ]
}

=== silagokth/vesyla/module/vs-component/components/controllers/sequencer/arch.json
{
  "kind": "sequencer",
  "size": 16,
  "io_input": false,
  "io_output": false,
  "custom_properties": [
    {
      "name": "NUM_SLOTS",
      "value": 16
    }
  ],
  "required_parameters": [
    "RESOURCE_INSTR_WIDTH",
    "NUM_SLOTS",
    "FSM_PER_SLOT",
    "INSTR_DATA_WIDTH",
    "INSTR_ADDR_WIDTH",
    "INSTR_HOPS_WIDTH"
  ]
}

=== silagokth/vesyla/module/vs-component/components/resources/iosram_top/arch.json
{
  "kind": "iosram_top",
  "size": 4,
  "io_input": true,
  "io_output": false,
  "custom_properties": [
    {
      "name": "SRAM_ADDR_WIDTH",
      "value": 6
    }
  ],
  "required_parameters": [
    "IO_DATA_WIDTH",
    "IO_ADDR_WIDTH",
    "RESOURCE_INSTR_WIDTH",
    "BULK_BITWIDTH",
    "WORD_BITWIDTH",
    "NUM_SLOTS",
    "FSM_PER_SLOT",
    "INSTR_OPCODE_BITWIDTH"
  ]
}

=== silagokth/vesyla/module/vs-component/components/resources/rf/arch.json
{
  "kind": "rf",
  "size": 1,
  "io_input": false,
  "io_output": false,
  "custom_properties": [
    {
      "name": "RF_DEPTH",
      "value": 64
    },
    {
      "name": "WORD_ADDR_WIDTH",
      "value": 6
    },
    {
      "name": "BULK_ADDR_WIDTH",
      "value": 2
    }
  ],
  "required_parameters": [
    "IO_DATA_WIDTH",
    "IO_ADDR_WIDTH",
    "RESOURCE_INSTR_WIDTH",
    "BULK_BITWIDTH",
    "WORD_BITWIDTH",
    "NUM_SLOTS",
    "FSM_PER_SLOT",
    "INSTR_OPCODE_BITWIDTH"
  ]
}

=== silagokth/vesyla/module/vs-component/components/resources/dpu/arch.json
{
  "kind": "dpu",
  "size": 2,
  "io_input": false,
  "io_output": false,
  "custom_properties": [],
  "required_parameters": [
    "IO_DATA_WIDTH",
    "IO_ADDR_WIDTH",
    "RESOURCE_INSTR_WIDTH",
    "BULK_BITWIDTH",
    "WORD_BITWIDTH",
    "NUM_SLOTS",
    "FSM_PER_SLOT",
    "INSTR_OPCODE_BITWIDTH"
  ]
}
